### ISSUE TITLE
`templateBranch` unused when cloning the template

### ISSUE THREAD

**Issue by oprypkhantc** [HanseltimeIndustries/template-repo-sync#9]
Hey!

If you specify a `templateBranch` with any other branch than the default one, it'll not be used. This is because `template-repo-sync-action` only passes the `repoUrl`, while `templateBranch` is only ever used for console logs and resulting branch name: https://github.com/HanseltimeIndustries/template-repo-sync-action/blob/main/src/sync-github-repo.ts#L144

Thank you for the awesome project :)

**Comment by hanseltime** [comment]
@oprypkhantc - Sorry about missing this.  I think I need to reconfigure my notifications.

Thank you for calling this out!

I will have a PR up soon to add this function and then wire it into the action

**Comment by hanseltime** [comment]
@oprypkhantc - updates have been applied to both this underlying library and the github action.  Thank you for submitting a bug report!
